name: restaurant_app
description: Restaurant App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  formz: ^0.4.1
  favorite_button: ^0.0.4
  path: ^1.8.0
  sqflite: ^2.0.0+3
  focus_detector: ^2.0.1
  flutter_local_notifications: ^9.7.0
  rxdart: ^0.27.4
  android_alarm_manager_plus: ^2.0.6
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  mockito: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
